-- Add first-class resources vertical

CREATE TABLE IF NOT EXISTS public.content_resource_category (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    slug character varying(80) NOT NULL,
    description text,
    sort_order integer NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
    updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE TABLE IF NOT EXISTS public.content_resource (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    description text NOT NULL DEFAULT ''::text,
    summary text NOT NULL DEFAULT ''::text,
    body text,
    link text NOT NULL,
    image_path text,
    slug text NOT NULL,
    status text NOT NULL DEFAULT 'draft'::text,
    date_created timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
    date_published timestamp with time zone,
    user_id bigint,
    resource_category_id bigint
);

CREATE TABLE IF NOT EXISTS public.content_resource_topics (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_id bigint NOT NULL,
    topic_id bigint NOT NULL
);

ALTER TABLE ONLY public.content_resource_category
    ADD CONSTRAINT content_resource_category_slug_key UNIQUE (slug);

ALTER TABLE ONLY public.content_resource
    ADD CONSTRAINT content_resource_link_key UNIQUE (link);

ALTER TABLE ONLY public.content_resource
    ADD CONSTRAINT content_resource_slug_key UNIQUE (slug);

ALTER TABLE ONLY public.content_resource
    ADD CONSTRAINT content_resource_user_id_fkey
        FOREIGN KEY (user_id) REFERENCES public.user_profiles(id);

ALTER TABLE ONLY public.content_resource
    ADD CONSTRAINT content_resource_resource_category_id_fkey
        FOREIGN KEY (resource_category_id) REFERENCES public.content_resource_category(id) ON DELETE SET NULL;

ALTER TABLE ONLY public.content_resource_topics
    ADD CONSTRAINT content_resource_topics_resource_id_topic_id_key UNIQUE (resource_id, topic_id);

ALTER TABLE ONLY public.content_resource_topics
    ADD CONSTRAINT content_resource_topics_resource_id_fkey
        FOREIGN KEY (resource_id) REFERENCES public.content_resource(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.content_resource_topics
    ADD CONSTRAINT content_resource_topics_topic_id_fkey
        FOREIGN KEY (topic_id) REFERENCES public.content_topic(id) ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS content_resource_status_idx ON public.content_resource USING btree (status);
CREATE INDEX IF NOT EXISTS content_resource_date_published_idx ON public.content_resource USING btree (date_published DESC);
CREATE INDEX IF NOT EXISTS content_resource_resource_category_id_idx ON public.content_resource USING btree (resource_category_id);
CREATE INDEX IF NOT EXISTS content_resource_topics_resource_id_idx ON public.content_resource_topics USING btree (resource_id);
CREATE INDEX IF NOT EXISTS content_resource_topics_topic_id_idx ON public.content_resource_topics USING btree (topic_id);

CREATE OR REPLACE FUNCTION public.generate_unique_resource_slug(input_title text)
RETURNS text
LANGUAGE plpgsql
AS $$
DECLARE
  base_slug text;
  new_slug text;
  counter integer := 1;
BEGIN
  base_slug := lower(coalesce(input_title, 'resource'));
  base_slug := regexp_replace(base_slug, '[^a-z0-9-]+', '-', 'g');
  base_slug := trim(both '-' from base_slug);

  IF base_slug = '' THEN
    base_slug := 'resource';
  END IF;

  new_slug := base_slug;

  WHILE EXISTS (SELECT 1 FROM public.content_resource WHERE slug = new_slug) LOOP
    counter := counter + 1;
    new_slug := base_slug || '-' || counter;
  END LOOP;

  RETURN new_slug;
END;
$$;

CREATE OR REPLACE FUNCTION public.set_slug_on_content_resource()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF NEW.slug IS NULL OR NEW.slug = '' THEN
    NEW.slug := public.generate_unique_resource_slug(NEW.title);
  END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.update_content_resource_category_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = timezone('utc'::text, now());
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS set_content_resource_slug ON public.content_resource;
CREATE TRIGGER set_content_resource_slug
BEFORE INSERT ON public.content_resource
FOR EACH ROW
EXECUTE FUNCTION public.set_slug_on_content_resource();

DROP TRIGGER IF EXISTS update_content_resource_category_updated_at ON public.content_resource_category;
CREATE TRIGGER update_content_resource_category_updated_at
BEFORE UPDATE ON public.content_resource_category
FOR EACH ROW
EXECUTE FUNCTION public.update_content_resource_category_updated_at();

INSERT INTO public.content_resource_category (name, slug, description, sort_order)
VALUES
  ('Fonts', 'fonts', 'Open source font libraries and collections', 1),
  ('Foundries', 'foundries', 'Independent and commercial type foundries', 2),
  ('Icon Libraries', 'icon-libraries', 'Icon packs and libraries for product design', 3),
  ('UI Kits', 'ui-kits', 'Ready-made UI kits for design and prototyping', 4),
  ('Design Systems', 'design-systems', 'Design system references and frameworks', 5),
  ('Component Libraries', 'component-libraries', 'Frontend component libraries and systems', 6),
  ('Toolkits', 'toolkits', 'General UX/design toolkits and bundles', 7)
ON CONFLICT (slug) DO NOTHING;

ALTER TABLE public.content_resource ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.content_resource_topics ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.content_resource_category ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON public.content_resource
    FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON public.content_resource_topics
    FOR SELECT USING (true);

CREATE POLICY "Enable read access for all users" ON public.content_resource_category
    FOR SELECT USING (true);

CREATE POLICY "Enable full access for admins" ON public.content_resource
    FOR ALL TO authenticated
    USING ((EXISTS (
      SELECT 1 FROM public.user_profiles
      WHERE user_profiles.user_id = auth.uid()
        AND user_profiles.is_admin = true
    )))
    WITH CHECK ((EXISTS (
      SELECT 1 FROM public.user_profiles
      WHERE user_profiles.user_id = auth.uid()
        AND user_profiles.is_admin = true
    )));

CREATE POLICY "Enable full access for admins" ON public.content_resource_topics
    FOR ALL TO authenticated
    USING ((EXISTS (
      SELECT 1 FROM public.user_profiles
      WHERE user_profiles.user_id = auth.uid()
        AND user_profiles.is_admin = true
    )))
    WITH CHECK ((EXISTS (
      SELECT 1 FROM public.user_profiles
      WHERE user_profiles.user_id = auth.uid()
        AND user_profiles.is_admin = true
    )));

CREATE POLICY "Enable full access for admins" ON public.content_resource_category
    FOR ALL TO authenticated
    USING ((EXISTS (
      SELECT 1 FROM public.user_profiles
      WHERE user_profiles.user_id = auth.uid()
        AND user_profiles.is_admin = true
    )))
    WITH CHECK ((EXISTS (
      SELECT 1 FROM public.user_profiles
      WHERE user_profiles.user_id = auth.uid()
        AND user_profiles.is_admin = true
    )));

CREATE POLICY "Enable full access for service role" ON public.content_resource
    FOR ALL TO service_role
    USING (true)
    WITH CHECK (true);

CREATE POLICY "Enable full access for service role" ON public.content_resource_topics
    FOR ALL TO service_role
    USING (true)
    WITH CHECK (true);

CREATE POLICY "Enable full access for service role" ON public.content_resource_category
    FOR ALL TO service_role
    USING (true)
    WITH CHECK (true);

GRANT ALL ON TABLE public.content_resource TO anon;
GRANT ALL ON TABLE public.content_resource TO authenticated;
GRANT ALL ON TABLE public.content_resource TO service_role;

GRANT ALL ON TABLE public.content_resource_topics TO anon;
GRANT ALL ON TABLE public.content_resource_topics TO authenticated;
GRANT ALL ON TABLE public.content_resource_topics TO service_role;

GRANT ALL ON TABLE public.content_resource_category TO anon;
GRANT ALL ON TABLE public.content_resource_category TO authenticated;
GRANT ALL ON TABLE public.content_resource_category TO service_role;

GRANT ALL ON SEQUENCE public.content_resource_id_seq TO anon;
GRANT ALL ON SEQUENCE public.content_resource_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.content_resource_id_seq TO service_role;

GRANT ALL ON SEQUENCE public.content_resource_topics_id_seq TO anon;
GRANT ALL ON SEQUENCE public.content_resource_topics_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.content_resource_topics_id_seq TO service_role;

GRANT ALL ON SEQUENCE public.content_resource_category_id_seq TO anon;
GRANT ALL ON SEQUENCE public.content_resource_category_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.content_resource_category_id_seq TO service_role;

GRANT ALL ON FUNCTION public.generate_unique_resource_slug(text) TO anon;
GRANT ALL ON FUNCTION public.generate_unique_resource_slug(text) TO authenticated;
GRANT ALL ON FUNCTION public.generate_unique_resource_slug(text) TO service_role;

GRANT ALL ON FUNCTION public.set_slug_on_content_resource() TO anon;
GRANT ALL ON FUNCTION public.set_slug_on_content_resource() TO authenticated;
GRANT ALL ON FUNCTION public.set_slug_on_content_resource() TO service_role;

GRANT ALL ON FUNCTION public.update_content_resource_category_updated_at() TO anon;
GRANT ALL ON FUNCTION public.update_content_resource_category_updated_at() TO authenticated;
GRANT ALL ON FUNCTION public.update_content_resource_category_updated_at() TO service_role;
