name: Process Content

on:
  schedule:
    - cron: '0 */4 * * *'  # Run every 4 hours
  workflow_dispatch:
    inputs:
      process_type:
        description: 'Type of processing to run'
        required: true
        default: 'feeds'
        type: choice
        options:
          - feeds
          - embed
          - both

jobs:
  process:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
      
      - name: Write env file
        run: |
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
          echo "SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" >> .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "PINECONE_API_KEY=${{ secrets.PINECONE_API_KEY }}" >> .env
          echo "PINECONE_INDEX_NAME=${{ secrets.PINECONE_INDEX_NAME }}" >> .env
      
      - name: Process content
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            node -r dotenv/config scripts/process-feeds.js ${{ github.event.inputs.process_type }}
          else
            node -r dotenv/config scripts/process-feeds.js feeds
          fi